export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_POST_DATA: 'SET_POST_DATA',
	UPDATE_POST_DATA: 'UPDATE_POST_DATA',
	DELETE_POST: 'DELETE_POST',
	GET_POSTS_DATA: 'GET_POSTS_DATA',
	OPEN_FORM: 'OPEN_FORM',
	CLOSE_FORM: 'CLOSE_FORM',
	RESET_POST_DATA: 'RESET_POST_DATA',
};


